### ISSUE TITLE
Namespaces for All Scripts?

### ISSUE THREAD

**Issue by RandomationGames** [RandomationGames/Randomation-Vehicle-Physics#15]
I am considering wrapping all of the scripts in the namespace "RVP" for smoother integration into projects.

**Comment by thelink2012** [comment]
That would be great, I've run across name collisions between RVP and some Unity Standard Assert before. 

Though will this break existing prefabs?

**Comment by RandomationGames** [comment]
I don't know, I'll try it when I have time.

**Comment by RandomationGames** [comment]
I added the RVP namespace to all scripts in the new branch "RVP_Namespace". Eventually I will merge it with the main branch.
