### ISSUE TITLE
Car bounce when open by Unity 5.5.1f1

### ISSUE THREAD

**Issue by tanakasama** [RandomationGames/Randomation-Vehicle-Physics#16]
When open project by Unity 5.5.1f1. Car will bounce while moving. Please check this bug.

**Comment by blakewoods** [comment]
Just checking - have you got the Global and Time Manager prefabs in the scene?

**Comment by tanakasama** [comment]
I have all of them. But seem, the behaviour of car like bouncing when moving.

**Comment by RandomationGames** [comment]
Can you describe this in more detail? I just tested it in the latest version of Unity and saw no unusual bouncing.

**Comment by tanakasama** [comment]
This is my bad. So, i will close this issue.
