### ISSUE TITLE
Car not stop when moving forward

### ISSUE THREAD

**Issue by tanakasama** [RandomationGames/Randomation-Vehicle-Physics#18]
When car moving forward that accel = 0, car will infinity moving with same velocity if car go forward, not go right or left...just go forward. Car never stop. Please check this bug.

**Comment by blakewoods** [comment]
You need to check out the axle friction variable

**Comment by tanakasama** [comment]
Where i can find axle friction variable. This should setting as default. Thanks in advanced.

**Comment by RandomationGames** [comment]
Axle friction is on the wheels. I think the default should be zero because it has a subtle effect on vehicle performance that might go unnoticed when configuring vehicles.
