### ISSUE TITLE
Calculate Tangents for Tire Marks

### ISSUE THREAD

**Issue by RandomationGames** [RandomationGames/Randomation-Vehicle-Physics#2]
Calculating tangents for tire mark meshes would allow for them to use materials with normal maps. This is useful for mud/snow tracks where they should appear to leave a impressions in the surface.

Tire marks are generated in the TireMarkCreate script. The tangent arrays should be handled similarly to the others such as vertex and uv.

**Comment by hemik1** [comment]
Hey! I'm not that familiar with GitHub, so would rather not commit it myself, but here's a dropbox link to a MeshUtil class with static CalculateMeshTangents method:
https://www.dropbox.com/s/rs373bcyex8b9r9/MeshUtil.cs?dl=0
And your script modified to make use of it, just 2 extra lines, first calculating Normals using unity's RecalculateNormals method and then doing the tangents (tangents require normals info):
https://www.dropbox.com/s/2s9un7chsiypmnj/TireMarkCreate.cs?dl=0

**Comment by RandomationGames** [comment]
Thanks, I'll take a look at this when I get a chance.

**Comment by RandomationGames** [comment]
Did you write the MeshUtil script or did someone else?

**Comment by hemik1** [comment]
The tangents calculating method i've found on the web, took one from this thread if I'm not mistaken: http://answers.unity3d.com/questions/7789/calculating-tangents-vector4.html
I've only moved some stuff around for optimization purposes (fewer pointer allocations).

**Comment by RandomationGames** [comment]
I have integrated your changes.
