### ISSUE TITLE
For easy drift behaviour 

### ISSUE THREAD

**Issue by tanakasama** [RandomationGames/Randomation-Vehicle-Physics#22]
Hi RandomationGames,

I want to make easy drift function but want to car stable, too. So how i can config the vehicle ? 

Thanks in advanced.

**Comment by RandomationGames** [comment]
You will definitely want to use the VehicleAssist script and tweak the drift variables to your liking.

For tire friction, the peak of the sideways friction curve affects how easily a vehicle starts drifting. If it's closer to the left or higher up, then the car will feel stiffer and harder to drift. If it is more to the right or lower then the steering will feel looser and more prone to slipping into a drift. The curve as a whole represents how much friction the tire has based on how much it is slipping.

You will also want to take a look at the slip dependence on the Wheel script, you can read about it in the manual.

There is no perfect setup, you will have to adjust it until it feels right for your vehicle.
