### ISSUE TITLE
Cast tyre collision

### ISSUE THREAD

**Issue by eliawestworld** [RandomationGames/Randomation-Vehicle-Physics#23]
I want to recreate with the raycast the motorcycle tire.
Multiple raycast in 3d direction or similar result.
Thanks for your help.

**Comment by RandomationGames** [comment]
I assume you want some kind of 3D tire functionality, where the wheel isn't just a raycast. There is already an issue for this: https://github.com/RandomationGames/Randomation-Vehicle-Physics/issues/10
