### ISSUE TITLE
Custom Map Issues

### ISSUE THREAD

**Issue by 7ekhed** [RandomationGames/Randomation-Vehicle-Physics#27]
I loaded into a custom map, and made a terrain. I grabbed the F1 car prefab, applied all of the scripts, but what I get is a car that has wheels moving, but no motion. Plz help

**Comment by RandomationGames** [comment]
One issue I've seen some users have is the wheels clipping into the ground and not detecting any collisions. The fix for this has been to adjust the wheel cast mask on the global control object/script to include the layer containing environmental geometry. If this isn't what your issue is then I would appreciate a video or a more in-depth description.

**Comment by 7ekhed** [comment]
What happens now is it goes a certain distance, then stops, then is unable to move again.

**Comment by 7ekhed** [comment]
P.S., im using 2.0.9

**Comment by RandomationGames** [comment]
Did you make any modifications to the muscle car prefab? The way the tire smoke particles are always emitting tells me that something wasn't set up correctly. I also see an error in the console and depending on where that is coming from, it could be stopping the execution of important scripts and resulting in the particle emission. Try to fix the errors and see if the problem goes away.

**Comment by 7ekhed** [comment]
I am unsure of the issue because it says that the issue has something to do with the TireMarkCreate.Update () function, and by taking a look at it, there appears to be nothing wrong
![incorrect](https://user-images.githubusercontent.com/35386913/36075993-7c244b74-0f24-11e8-849d-d4c7529ccb35.PNG)

**Comment by RandomationGames** [comment]
Is the Ground Surface Master configured properly on the GlobalControl object? If you used the prefab of the object then it should be. Make sure there is only one instance in the scene.

**Comment by 7ekhed** [comment]
It is, but turning is now the issue, and the engine just stops after i stop moving, and doesnt want to respond, so im very confused as to what its doing

**Comment by 7ekhed** [comment]
Also, is it possible to use your map in a public game?

**Comment by 7ekhed** [comment]
And one last question, how can I modify the prefabs, because when i try and save a prefab, none of the textures show up

**Comment by RandomationGames** [comment]
I'm sorry but I don't know what could be causing the issue. It could be anything from a mistake made when setting things up or the fact that you're using Unity 2017, which I have not tested my vehicle physics with. I have not used Unity 2017 at all, so I don't know how applying prefabs could be breaking the textures.

You could try using unity 5.6.1 and see if any of the problems show up. If they don't, then we'll know that something about opening the package in Unity 2017 is breaking things.

You can use the map in a public game as the models in the package are public domain.

**Comment by 7ekhed** [comment]
Ok, thanks for helping, and thank you for responding. I will try in another version of unity! thanks!
